#cloud-config
apt_update: true
users:
  - name: deployer
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIp+P2hKAXiFfGTT1gfAJekcE0mr3b7m5hBv056WCFLPCLRUPu82VOO6MfAhnKNI5lEDoOK6yOc2zo0T9zkTA9eWCTp22aEj9VWmXX+f3tnkOyJJSYpO8uYt97O7ip5jS+Ek1aKzSkX0u9KRsKfioJ8ZrGX5Xw9rMoYjeYJb+XD9zF42XNjn5cD9r628xdBFxZ6ZkZ0ycerPc56FokW3l/c2XJTKybb68qo0F6S5MkB75fMxm3ojBwyJELteExVR9JdPFjf3N71sjz7E7W6vFp/QFAdXmQuqapxVgoFgrdyA6NSK5yBaVeUUKyBqPn5u2q5gwcglDX9xU/MoeXNiMglUtcVboHCdbAnOxyicQnggr1jYIuaYeHKTL+LUSCnk0Eh2e4EfZIAdPVodnt7hunD5vl8VeGzprTrTjQghFI60QvpiMSun/zZPV2ND6PCNy+Eu01Sqk+r54mJlZko0fLMD61ighxId7XMG396p6HJ0US3hnoH/UbBImwG+E6GhiRgzH37/6Qny3vmly13S2ijwtBALiHMMIFB6GXppLS8NHotHsnRLIz7FC2/CTs4NBZG6EtSMpmqhWw6+6jBAF4jy/o870G5zDc7tZWIzMwU7akKWcPX7lLXAFANjDstLjmrbZ6NlrPkeGlSoboLD25UIK+CmEKoVkf1KStgVQ0aw== rirussel@ubuntu-s-1vcpu-1gb-ams3-01'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7aujHg0gb6uBpOVoiRN01vJQAliNIyeyzIFn9Q6RWe8LtJBgPmzaqERBLbcx9IVhQExFqQHz44Fb/JR54N5LOueXBsj4DEPl0RQVjpLUg3oNFwNBtbxMVDF0ZMsG4/9rvNQUVFNdZR0fOkzFPTfXwtjdW3Dt6oMIeoMJelzGWbitZS0KCYl+jCxoQF9tfTMg+LQRsqhRbkDdL0Yk+TaOvrAdSlKuxBs86kyzvYF/jQNNeuHNGCCe9mGSwy8nw6IGhXs2n1IVIRv1TgMl+TUQcWXu5yAUd1OPrO220ZrGTGonr98bleNTnTmTlr8Xsd+K95mLWBXRc5Icqw6KPqEbfHsTCcN1MI+RkDGZVvqq6/tMKGLMxI4sySyZ1ewSFNL/1mp7oKwErGr2LseIJLcuXyNXh/fStwlLAOKZfbtZr7TRHjcnovFsUae57rCxvu9yYopBNTi5uW/EFmCDd57Rgw5foajni7+JJNO/VWz0QDuafTJxVkWP+e3L4ISCs8bekHzx8F2SU+ChA8LSF+54seMsDqDLmUaFY7tEI9aOKY3Xdqa+gKg2rclss5b0U0uMA3aelktrshcQQIJcFn6xZKBZHe0Mpsk6puXoIFy3T5iRpA6gWT0AqGU5PyVreg1kzrQAjkyb4SuWtVsSrxZ6ck7CCDyPioo30yO1ZdoW83w== russel@MacBook-Pro-1.local'
packages:
    - python
    - python-apt
    - python3-apt
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
