---
  - hosts: vm_instances
    become: true
    tasks:
      - name: Update apt packages
        apt: upgrade=yes update_cache=yes
        when: ansible_facts['os_family'] == "Debian"
      - name: "Install PXE TFTP utilities"
        apt:
          name: "{{ packages }}"
        vars:
          packages:
          - apache2
          - tftpd-hpa
          - inetutils-inetd
          - isc-dhcp-server
      - name: "Update the tftp configuration"
        blockinfile:
          path: /etc/default/tftpd-hpa
          block: |
            RUN_DAEMON="yes"
            OPTIONS="-l -s /var/lib/tftpboot"
      - name: "Update inetd.conf"
        blockinfile:
          path: /etc/inetd.conf
          block: |
            tftp    dgram   udp    wait    root    /usr/sbin/in.tftpd /usr/sbin/in.tftpd -s /var/lib/tftpboot
      - name: "Restart TFTP services"
        systemd:
          state: restarted
          name: tftpd-hpa
      - name: "Create directory for downloaded ISOs"
        file:
          path: /mnt/iso-storage
          state: directory
          mode: '0755'
      - name: "Grab Ubuntu ISO for testing PXE boot"
        get_url:
          url: http://releases.ubuntu.com/16.04/ubuntu-16.04.6-server-amd64.iso
          dest: /tmp/ubuntu-16.04.6-server-amd64.iso
          mode: '0644'
        register: get_ubuntu_iso
      - debug: 
          msg="ISO already downloaded"
        when: get_ubuntu_iso|changed
      - name: Mount Ubuntu server ISO read-only
        mount: 
          path: /mnt/iso-storage
          src: /tmp/ubuntu-16.04.6-server-amd64.iso
          fstype: iso9660
          opts: ro,loop
          state: mounted
      - name: Synchronize two directories on one remote host.
        synchronize:
          src: /mnt/iso-storage/install/netboot/
          dest: /var/lib/tftpboot/
        delegate_to: "{{ inventory_hostname }}"
      - name: "Update PXE server configuration"
        blockinfile:
          path: /var/lib/tftpboot/pxelinux.cfg/default
          block: |
            label linux
            kernel ubuntu-installer/amd64/linux
            append ks=http://10.185.160.235/ks.cfg vga=normal initrd=ubuntu-installer/amd64/initrd.gz ramdisk_size=16432 root=/dev/rd/0 rw  --
      - name: "Update DHCP server configuration"
        blockinfile:
          path: /etc/dhcp/dhcpd.conf
          block: |
            allow booting;
            allow bootp;
            option option-128 code 128 = string;
            option option-129 code 129 = text;
            next-server 10.185.160.223;
            filename "pxelinux.0";
      - name: Set dhcp server interface  
        lineinfile:
          path: /etc/default/isc-dhcp-server
          regexp: 'INTERFACESv4=""'
          line: 'INTERFACESv4="eth0"'
      - name: Set domain for dhcp
        lineinfile:
          path: /etc/dhcp/dhcpd.conf
          regexp: 'option domain-name "example.org";'
          line: 'option domain-name "cdetesting.com";'
      - name: Set dhcp nameservers 
        lineinfile:
          path: /etc/dhcp/dhcpd.conf
          regexp: 'option domain-name-servers ns1.example.org, ns2.example.org;'
          line: 'option domain-name-servers pxe.cdetesting.com;'
      - name: Set dhcp as authoritative 
        lineinfile:
          path: /etc/dhcp/dhcpd.conf
          regexp: '#authoritative;'
          line: 'authoritative;'
      - name: Set DHCP IP range 
        blockinfile:
          path: /etc/dhcp/dhcpd.conf
          block: |
             subnet 10.184.236.144 netmask 255.255.255.248 {
             range 10.184.236.146 10.184.236.150;
             option domain-name-servers pxe.cdetesting.com;
             option domain-name "cdetesting.com";
             option routers 10.184.236.145;
             option broadcast-address  10.184.236.151;
             default-lease-time 600;
             max-lease-time 7200;
      - name: "Restart DHCP server"
        systemd:
          state: restarted
          name: isc-dhcp-server